---
default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [--unsafe]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.17.0
    hooks:
      - id: yamllint
        entry: yamllint -s
        files: .*\.(json|yml|yaml)$
        exclude: duckdns-pi-role/vars/main.yml

#  - repo: https://github.com/ansible-community/ansible-lint.git
#    rev: v6.14.2
#    hooks:
#      - id: ansible-lint
#        files: \.(yaml|yml)$
