# Docker ubuntu

- name: Install docker dependencies
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release


- name: Create docker keyring directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add an Apt signing key to a specific keyring file
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg

- name: Chmod a+r /etc/apt/keyrings/docker.gpg
  file:
    path: /etc/apt/keyrings/docker.gpg
    owner: root
    group: root
    mode: '0644'

- name: Install docker (stable) repo
  command:
    cmd: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: apt-get update
  apt:
    update_cache: yes

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: Install docker
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin


- name: Add user pi to docker user-group
  user:
    name: "{{ ansible_facts['user_id'] }}"
    group: docker
    append: yes

- name: Start / Enable Docker
  service:
    name: docker
    state: started
    enabled: true