---
# tasks file for setup-pi

- name: apt-get update
  apt:
    update_cache: true

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: Add Fan Control
  template:
    src: templates/firmware_config.txt.j2
    dest: /boot/firmware/config.txt
    #backup: yes
    owner: root
    group: root
    mode: '0755'

- name: Install pip
  apt:
    name: python3-pip
    state: present

- include: docker.yml
